// Shared Node/workerd vectors. Expected values describe JS strict-null authority,
// not SQLite json_extract (which selects the first duplicate key).
export const runRoomCases:Array<{context:string;allowed?:boolean;error?:string;fallback?:boolean}>=[
 {context:'{"room_id":null}',allowed:true},
 {context:'{"room_id":"foreign"}',allowed:false},
 {context:'{"room_id":false}',allowed:false},
 {context:'{"room_id":0}',allowed:false},
 {context:'{"room_id":""}',allowed:false},
 {context:'{"room_id":{}}',allowed:false},
 {context:'{"room_id":[]}',allowed:false},
 {context:'{}',allowed:false},
 {context:'{"nested":{"room_id":null}}',allowed:false},
 {context:'{"room_id":null,"room_id":"foreign"}',allowed:false,fallback:true},
 {context:'{"room_id":"foreign","room_id":null}',allowed:true,fallback:true},
 {context:'{"room_id":null,"\\u0072oom_id":false}',allowed:false,fallback:true},
 {context:'{"room_id":false,"\\u0072oom_id":null}',allowed:true,fallback:true},
 {context:'{"room_id\\u0000":null}',allowed:false},
 {context:'{"room_id":null,"room_id\\u0000":false}',allowed:true},
 {context:'{"r\\u0000oom_id":null}',allowed:false},
 {context:'{"\\ud800room_id":null}',allowed:false},
 {context:'{"room_id":null,"other":1e999}',allowed:true},
 {context:'{"__proto__":{"room_id":null}}',allowed:false},
 {context:'[]',allowed:false,fallback:true},
 {context:'"room_id"',allowed:false,fallback:true},
 {context:'1',allowed:false,fallback:true},
 {context:'false',allowed:false,fallback:true},
 {context:'null',error:'TypeError',fallback:true},
 // SQLite's json_valid CHECK admits trailing raw NULs; JS rejects them.
 {context:'{"room_id":null}\u0000ignored',error:'SyntaxError',fallback:true},
 {context:JSON.stringify({room_id:null,padding:'界'.repeat(400000)}),allowed:true},
 ...Array.from('room_id',(_,i)=>({context:'{"'+Array.from('room_id',(c,j)=>i===j?'\\u'+c.charCodeAt(0).toString(16).padStart(4,'0'):c).join('')+'":null}',allowed:true})),
];
