// Secret names only; values are set through Wrangler secret bindings, never committed.
declare namespace Cloudflare {
 interface Env { HEHEBOT_TEST_REVOKED?:string; }
 interface Env { HEHEBOT_TEST_ACCESS?:string; HEHEBOT_TEST_CAMPAIGN?:string; }
 interface Env { HEHEBOT_OWNER_ALPHA_BOOTSTRAP?:string; HEHEBOT_OWNER_ALPHA_MANAGER_TOKEN?:string; HEHEBOT_OWNER_ALPHA_TASK_SIGNING_KEY?:string; }
 interface Env { HEHEBOT_OWNER_ALPHA_WAKE?:string; HEHEBOT_OWNER_ALPHA_WAKE_TOKEN?:string; }
 interface Env { HEHEBOT_OWNER_ALPHA_WARM_GENERATION?:string; HEHEBOT_OWNER_ALPHA_HOST_SIGNING_KEY?:string; }
 interface Env { HEHEBOT_OWNER_ALPHA_BACKGROUND_GENERATION?:string; HEHEBOT_OWNER_ALPHA_BACKGROUND_HOST_SIGNING_KEY?:string; HEHEBOT_OWNER_ALPHA_BACKGROUND_TASK_SIGNING_KEY?:string; }
 interface Env { HEHEBOT_BOOT_DEADLINE_MS?:string; HEHEBOT_SUCCESSOR_BACKOFF?:string; HEHEBOT_RUNTIME_GENERATION?:string; HEHEBOT_OWNER_ALPHA_SUCCESSOR?:string; HEHEBOT_HOSTED_OWNER_ALPHA?:string; HEHEBOT_OWNER_ALPHA?:string; NATIVE_DELEGATIONS?:string; FLIGHT_RESTORE_VERIFIED?:string; FLIGHT_RESTORE_POLICY_ID?:string; PROVIDER_TOKEN?: string; SPRITE_WAKE_TOKEN?: string; RUNTIME_TOKEN?: string; TRIGGER_SECRETS?: string; }
}

interface Env { HEHEBOT_TEST_REVOKED?:string; }
interface Env { HEHEBOT_TEST_ACCESS?:string; HEHEBOT_TEST_CAMPAIGN?:string; }
interface Env { HEHEBOT_OWNER_ALPHA_BOOTSTRAP?:string; HEHEBOT_OWNER_ALPHA_MANAGER_TOKEN?:string; HEHEBOT_OWNER_ALPHA_TASK_SIGNING_KEY?:string; }
interface Env { HEHEBOT_OWNER_ALPHA_WAKE?:string; HEHEBOT_OWNER_ALPHA_WAKE_TOKEN?:string; }
interface Env { HEHEBOT_OWNER_ALPHA_WARM_GENERATION?:string; HEHEBOT_OWNER_ALPHA_HOST_SIGNING_KEY?:string; }
interface Env { HEHEBOT_OWNER_ALPHA_BACKGROUND_GENERATION?:string; HEHEBOT_OWNER_ALPHA_BACKGROUND_HOST_SIGNING_KEY?:string; HEHEBOT_OWNER_ALPHA_BACKGROUND_TASK_SIGNING_KEY?:string; }
interface Env { HEHEBOT_BOOT_DEADLINE_MS?:string; HEHEBOT_SUCCESSOR_BACKOFF?:string; HEHEBOT_RUNTIME_GENERATION?:string; HEHEBOT_OWNER_ALPHA_SUCCESSOR?:string; HEHEBOT_HOSTED_OWNER_ALPHA?:string; HEHEBOT_OWNER_ALPHA?:string; NATIVE_DELEGATIONS?:string; FLIGHT_RESTORE_VERIFIED?:string; FLIGHT_RESTORE_POLICY_ID?:string; PROVIDER_TOKEN?: string; SPRITE_WAKE_TOKEN?: string; RUNTIME_TOKEN?: string; TRIGGER_SECRETS?: string; }
