import type {FlightRegistration,FlightReceipt,FlightReconciliation} from './flight-integration';
import type { Identity, HeartbeatOperation, CoordinatorOutcome } from './lifecycle';
import type {NativeChildReceipt} from './native-tasks';
import type { EffectIntent } from './effects';
import type {AgentCommandRequest,AgentRoutineQuery,AgentSkillQuery,AgentSkillSearch} from './agent-commands';
import type {RootChildEffectIntent,RootChildEffectResult} from './root-child-effects';
import type {BudgetReport} from './budget';
import type {SteeringTarget,SteeringOutcome} from './task-steering';
import type {OutputPreview} from './output-preview';
import type {TokenUsageSnapshot} from './token-usage';
import type {NativeQuestionInput} from './native-questions';
import type {WhatsAppReadRequest} from './whatsapp-access';
import type {TextOnlyProfile} from './owner-alpha';
import type {MemoryBudgetReceipt} from './memory-context';
type Base={identity:Identity};type Attempt={run_id:string;attempt:number};
export type TextOnlyReceipt=TextOnlyProfile&{thread_id:string;turn_id:string;output_sha256:string};
export type BackgroundReceipt={thread_id:string;turn_id:string;output_sha256:string};
export type RuntimePayloads={
 status:Record<string,never>;
 'whatsapp-read-authorize':WhatsAppReadRequest;
 'question-record':Base & Attempt & {question:NativeQuestionInput};
 'question-take':Base & {question_id:string;connection_id:string};
 'question-resolve':Base & {question_id:string;connection_id:string};
 'output-preview':Base & OutputPreview;
 'token-usage':Base & TokenUsageSnapshot;
 'steer-pending':Base & {targets:SteeringTarget[]};
 'steer-result':Base & SteeringTarget & {command_id:string;status:SteeringOutcome};
 'budget-report':Base & Attempt & {report:BudgetReport};
 'flight-register':FlightRegistration;
 'flight-confirm':FlightReceipt;
 'flight-reconcile':FlightReconciliation;
 'native-child':Base & {child:NativeChildReceipt;started?:boolean};
 'resource-acquire':Base & Attempt & {resources:string[]};
 'resource-release':Base & Attempt & {resources:string[]};
 boot:{boot_id:string};ready:Base;claim:Base & {persona_models?:Record<string,string>;memory_budget?:MemoryBudgetReceipt};
 'memory-prepare':Base & {persona_models:Record<string,string>};
 heartbeat:Base & {operations:HeartbeatOperation[]};
 submitted:Base & Attempt & {native_ref:string};
 'coordinator-release':Base & Attempt & {native_ref:string;outcome:CoordinatorOutcome};
 complete:Base & Attempt & {result:{status:'completed'|'failed'|'cancelled'|'waiting';text:string;error_code?:string;checkpoint?:Record<string,unknown>};text_only_receipt?:TextOnlyReceipt;background_receipt?:BackgroundReceipt};
 'prepare-sleep':Base;
 'commit-sleep':Base & {stop_token:string;queue_sequence:number;checkpoint:Record<string,unknown>};
 'effect-intent':Base & {effect:EffectIntent};
 'effect-result':Base & Attempt & {effect_id:string;status:'dispatched'|'confirmed'|'failed'|'outcome_unknown';receipt:Record<string,unknown>|null};
 'root-child-effect-intent':RootChildEffectIntent;
 'root-child-effect-result':RootChildEffectResult;
 'agent-command':AgentCommandRequest;
 'agent-routines':AgentRoutineQuery;
 'agent-skill':AgentSkillQuery;
 'agent-skill-search':AgentSkillSearch;
};
export type RuntimeCommand={ [K in keyof RuntimePayloads]:{type:K;payload:RuntimePayloads[K]} }[keyof RuntimePayloads];
